#!/usr/bin/env bash

if [ -z "${TIMEZONE}" ]; then
  TIMEZONE="Etc/UTC"
fi

export FACTER_TIMEZONE="${TIMEZONE}"

if [ -z "${GENERAL_LOG}" ]; then
  GENERAL_LOG="0"
fi

export FACTER_GENERAL_LOG="${GENERAL_LOG}"

if [ -z "${SLOW_QUERY_LOG}" ]; then
  SLOW_QUERY_LOG="0"
fi

export FACTER_SLOW_QUERY_LOG="${SLOW_QUERY_LOG}"

if [ -z "${LONG_QUERY_TIME}" ]; then
  LONG_QUERY_TIME="1"
fi

export FACTER_LONG_QUERY_TIME="${LONG_QUERY_TIME}"

if [ -z "${QUERY_CACHE_TYPE}" ]; then
  QUERY_CACHE_TYPE="0"
fi

export FACTER_QUERY_CACHE_TYPE="${QUERY_CACHE_TYPE}"

if [ -z "${QUERY_CACHE_SIZE}" ]; then
  QUERY_CACHE_SIZE="1M"
fi

export FACTER_QUERY_CACHE_SIZE="${QUERY_CACHE_SIZE}"

if [ -z "${QUERY_CACHE_LIMIT}" ]; then
  QUERY_CACHE_LIMIT="1M"
fi

export FACTER_QUERY_CACHE_LIMIT="${QUERY_CACHE_LIMIT}"

if [ -z "${QUERY_CACHE_MIN_RES_UNIT}" ]; then
  QUERY_CACHE_MIN_RES_UNIT="4K"
fi

export FACTER_QUERY_CACHE_MIN_RES_UNIT="${QUERY_CACHE_MIN_RES_UNIT}"

if [ -z "${MAX_ALLOWED_PACKET}" ]; then
  MAX_ALLOWED_PACKET="16M"
fi

export FACTER_MAX_ALLOWED_PACKET="${MAX_ALLOWED_PACKET}"

if [ -z "${KEY_BUFFER_SIZE}" ]; then
  KEY_BUFFER_SIZE="16M"
fi

export FACTER_KEY_BUFFER_SIZE="${KEY_BUFFER_SIZE}"

if [ -z "${THREAD_CACHE_SIZE}" ]; then
  THREAD_CACHE_SIZE="8"
fi

export FACTER_THREAD_CACHE_SIZE="${THREAD_CACHE_SIZE}"

if [ -z "${INNODB_BUFFER_POOL_SIZE}" ]; then
  INNODB_BUFFER_POOL_SIZE="128M"
fi

export FACTER_INNODB_BUFFER_POOL_SIZE="${INNODB_BUFFER_POOL_SIZE}"

if [ -z "${INNODB_FLUSH_LOG_AT_TRX_COMMIT}" ]; then
  INNODB_FLUSH_LOG_AT_TRX_COMMIT="1"
fi

export FACTER_INNODB_FLUSH_LOG_AT_TRX_COMMIT="${INNODB_FLUSH_LOG_AT_TRX_COMMIT}"
